### ISSUE TITLE
'Type' and 'Show' filtering sometimes does not filter newly loaded videos/live streams

### ISSUE THREAD

**Issue by Braboware** [Dinger1112/BetterYouTubeSubs#15] opened 2022-01-07 04:08 UTC
Version: 0.16.1

Sometimes after choosing the 'live streams' option on the 'type' drop down, currently loaded videos get hidden, leaving the live streams. However, scrolling down to load more videos loads a mix of videos and live streams. Choosing the 'live streams' option again hides the newly loaded videos, but its inconvenient because it requires scrolling back up to choose the drop down option.

Same happens with the other filters 'videos', 'unwatched', 'continue watching', and 'finished'.

Not sure what causes it. As I was typing this up, the filtering on my normal firefox installation resolved itself, but the filtering on my ESR installation still had the same problem.

**Comment by Dinger1112** [comment] 2022-01-07 22:53
i was able to reproduce the problem on an ESR version of firefox, will look into a fix as soon as i'm able

**Comment by Dinger1112** [comment] 2022-01-08 00:51
though i can't confirm with certainty as i do not have the environment the issue was first found on, due to the nature of the bug i just fixed, i find it to be the most likely cause of the issue so i will close it for now

**Closed by Dinger1112** 2022-01-08 00:51 UTC
